### ISSUE TITLE
[FEATURE REQUEST] Waxed copper / oxidized copper compatibility

### ISSUE THREAD

**Issue by Voltem0** [CERBON-MODS/CERBONs-Better-Beacons-FORGE#1]
## Before submitting the issue

- [x ] **I have checked that the requested feature is not a duplicate or, if it is, it needs to be reopened**
- [x ] **I have checked that I am running the latest version of Better Beacons Mod**
- [x ] **I have checked the [FAQ](https://github.com/CerbonXD/BetterTotemOfUndying/blob/master/FAQ.md) section**
- [x ] **I have read the [contributing guidelines](https://github.com/CerbonXD/BetterTotemOfUndying/blob/master/CONTRIBUTING.md#feature-requests) and I agree with the [Code of Conduct](https://github.com/CerbonXD/BetterTotemOfUndying/blob/master/CODE_OF_CONDUCT.md)**
- (this template needs an update, i am commenting about better-beacons not better-totem-of-undying)

## Is your feature request related to a problem? Please describe.
Hello
When i build a beacon pyramid out of copper blocks with the better beacons mod, the mod works great.
However, eventually that copper oxidizes and the beacon stops working.
Waxed copper blocks are not accepted by the mod and oxidized copper isnt either, so the beacons function for a limited time.

## Describe the solution you'd like
I would like to ask if the beacon can accept either oxidized copper blocks or waxed copper blocks, that way i can continue to use copper blocks and either let them oxidize in peace or have to wax them first (tedious but ok).

## Describe alternatives you've considered
Alternatively, copper blocks that form the base of a beacon could be made oxidization proof? not sure how you would do that but might as well bring it up.

**Comment by CerbonXD** [comment]
Oh, I forgot that Waxed Copper is a different block🤦‍♂️. I will definitely add it. I'm not sure about the oxidized versions tho, but I think that I will also add it to make the copper beacon less annoying. I will probably update it by tomorrow. Thanks for sharing you idea.

**Comment by CerbonXD** [comment]
I've updated the mod (v1.0.1), now you can use all copper variants to build the beacon.
