### ISSUE TITLE
[BUG/ISSUE]  Mod crashes when used on servers

### ISSUE THREAD

**Issue by guydkilller** [CERBON-MODS/CERBONs-Better-Beacons-FORGE#2]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of Better Beacons Mod**
- [x] **I have checked the [FAQ](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/blob/master/FAQ.md) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/blob/master/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/blob/master/CODE_OF_CONDUCT.md)**

## Minecraft Version
1.20.1
## Describe the bug
world crashing and unable to re-enter 

## To Reproduce
i built an iron 7x7 pyramid  for the beacon put the beacon right clicked it and boom world crashed

## Expected behavior
i wanted to put a beacon and the game crashed when i right clicked the beacon
## Latest Log

<details>

```
[crash minecraft.txt](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/files/13229525/crash.minecraft.txt)


</details>

## Additional context
its a hosted multiplayer server using the create hevan modpack

**Comment by CerbonXD** [comment]
Seems to be an incompatibility with servers... I don't know exactly why but I will take a look and see if I can fix it. You can't join the server because the code that is crashing it is updated every 4 seconds. I will try fix it by tomorrow. Sorry about that btw.

**Comment by CerbonXD** [comment]
It should be working now at version 1.0.2. Please update the mod and see if t's working for you.
