### ISSUE TITLE
[FEATURE REQUEST] Configuration for Block Amplification / modded block types

### ISSUE THREAD

**Issue by PlayfulPiano** [CERBON-MODS/CERBONs-Better-Beacons-FORGE#3]
Basically this is a suggestion to allow the user to add custom block types to be used for the beacon amplification mechanic, whether those are modded or vanilla blocks (but realistically for modded blocks designed to be more valuable than netherite).

Prime example in my case would be the Advanced Netherite mod, which has new blocks of Netherite-Iron all the way to Netherite-Diamond. I would personally config this so Netherite-Emerald is +4 and Netherite-Diamond is +5, for example.

**Comment by CerbonXD** [comment]
You can already do it. Take a look at the [wiki](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/wiki/Datapack) to see how to add the blocks.

**Comment by PlayfulPiano** [comment]
Ah I didn't catch that, thank you.

**Comment by PlayfulPiano** [comment]
Do you happen to have an example datapack with the folder and file structure for this? I'm not exactly sure how I'm supposed to setup the designated folders.
