### ISSUE TITLE
[BUG/ISSUE] Crash without BFA when Connector is installed

### ISSUE THREAD

**Issue by Fnige** [CERBON-MODS/CERBONs-Better-Beacons-FORGE#4]
## Before submitting the issue

- [x] **I have checked that the bug is not a duplicate or, if it is, it needs to be reopened**
- [x] **I have checked that I am running the latest version of Better Beacons Mod**
- [x] **I have checked the [FAQ](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/blob/master/FAQ.md) section for solutions**
- [x] **I have read the [contributing guidelines](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/blob/master/CONTRIBUTING.md#issues) and I agree with the [Code of Conduct](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/blob/master/CODE_OF_CONDUCT.md)**

## Minecraft Version
Version of Minecraft you are running the mod on
1.20.1

## Describe the bug

Game crashes when launching with BB without also having Beacons for all installed

## To Reproduce

1. Have Better beacons installed
2. Dont have beacons for all installed
3. Launch :3

## Latest Log

<details>

Error: https://gist.github.com/Fnige/4ee2ed5c870ba8dd8185882cbab89638
Full Log: https://gist.github.com/Fnige/c83af373ee2178aef8c6f7dcc13789bb

</details>

**Comment by CerbonXD** [comment]
That's really weird. It does not happen to me. Also, before I call his class I check if his mod is installed first.

Can you please test if it also happens in a new instance? With only my mod installed?

**Comment by Fnige** [comment]
Interestingly enough, it does not seem to happen with CBB on its own which is weird. Might try and figure out which mod is causing this when I wake up next

**Comment by Fnige** [comment]
Aha, figured out that it happens with Sinytra Connector + CBB
https://gist.github.com/Fnige/8f5083ec34bc15ae85192e9aafe9d62f

Why? I dont know but those people might

**Comment by CerbonXD** [comment]
Connector is still very unstable, I think. It might be changing something that is making it happen. II probably can't do much about it.

**Comment by PlayfulPiano** [comment]
Quick update here but the latest beta of Sinytra (v29) should have this issue fixed.
