### ISSUE TITLE
Mod Causes "Just Enough Beacon's" Beacon Frame Blocks & Payment Tabs/Pages Not to Load

### ISSUE THREAD

**Issue by DumbXBoxAcct** [CERBON-MODS/CERBONs-Better-Beacons-FORGE#7]
## Minecraft Version
1.20.1 / Forge 47.2.0

## Describe the bug
When "Better Beacons" v.1.1.1 is loaded, Just Enough Beacons' (JEB) v.1.1.1 "Beacon Frame Blocks" & "Beacon Payment" Tabs don't appear.  The "Conduit Frame Blocks" tab still appears without an issue, though.  When "Better Beacons" is not loaded, all three JEB tabs appear normally.  "Cerbon's API" v.1.0.0 can be loaded or not loaded, it doesn't cause the issue.

## To Reproduce
1. Unloaded all mods EXCEPT:

- Optifine 1.20.1_HD_U_I6
- Better Beacon Placement 3.1
- Biomes O'Plenty
- Cerbons Better Beacons
- CerbonsAPI v 1.0.0
- Collective 7.28
- Just Enough Items 15.2.0.27
- Just Enough Beacons 1.1.1
- Terrablender 3.0.0.169

2. Opened JEI, searched for and clicked the Beacon item, then right-clicked it.  Right-Clicking left the Crafting page open and did nothing.  The tabs for the Frame Blocks and Payment pages didn't appear.
3. Opened JEI, searched for and clicked the Conduit item, then right-clicked it.  The Conduit Frame Blocks tab and page appeared.
4. Closed Minecraft
5. Removed Cerbon's Better Beacons from the Minecraft Mods folder.
6. Ran Minecraft.
7. Opened JEI, searched for and clicked the Beacon item, then right-clicked it.  This time the Frame Blocks and Payments tabs/pages appeared correctly.

## Expected behavior
On right-clicking the Beacon item in JEI, tabs should appear on the JEI box for Beacon Frame Blocks and Beacon Payments. Clicking on these tabs should open panels in the JEI box which show information for both items.

## Screenshots
![Loaded](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/assets/115334190/20f31335-8dd0-4b16-abc7-d31453ced8ef)
![Unloaded](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/assets/115334190/5ac7a341-113a-45fd-a0df-7eb6627baae5)

## Latest Log

<details>

```
[latest.log](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/files/13997234/latest.log)
```
[debug.log](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/files/13997248/debug.log)

**Comment by CerbonXD** [comment]
Thanks for letting me know about this issue, the version 1.1.2 should have it fixed. Please test and let me know if it's working fine for you.

**Comment by DumbXBoxAcct** [comment]
Great!  But where can I download 1.1.2?  Curseforge's most recent is 1.1.1, as you can see below, and I don't see the mod on Modrinth.

![Curseforge](https://github.com/CERBON-MODS/CERBONs-Better-Beacons-FORGE/assets/115334190/34fefcf6-c945-43d3-bc19-e9c894413adf)

**Comment by CerbonXD** [comment]
Sorry, I didn't explain it well. Its 1.1.2 of Just Enough Beacons.

**Comment by DumbXBoxAcct** [comment]
All set!  Works perfectly & even shows copper as a payment type.  Thanks so much you for fixing it so quickly!

Also, something you may want to consider for 1.1.3: The three effects which you introduce in Better Beacons don't show descriptions when you look at them with Just Enough Effect Descriptions (JEED) v.2.1.7.  If you add the following lines under each effect's declaration in your language file, it'll give them descriptions.  I tried it out by modifying en-us.json manually and it worked for me.

"effect.better_beacons.phantom_bane.description": "Prevents phantoms from spawning within the beacon's range.",
"effect.better_beacons.patrol_nullifier.description": "Prevents patrols from spawning within the beacon's range.",
"effect.better_beacons.long_reach.description": "Increases the range at which players can interact with blocks.",

Going to close this out, now, thank you again, I really appreciate your work!

**Comment by CerbonXD** [comment]
Thank you for the suggestion, I will add it to the next update.
